# Pandas and NumPy

This notebook covers the fundamentals of Pandas and NumPy used in
data processing and exploratory data analysis.

## Learning Objectives

- Understand NumPy arrays and their properties
- Perform numerical operations using NumPy
- Understand Pandas Series and DataFrames
- Load and inspect datasets using Pandas
- Select, filter, and modify data
- Perform basic data processing operations

In [5]:
import numpy as np
import pandas as pd

## What is NumPy?

NumPy (Numerical Python) is a Python library used for numerical
computing.

It provides the `ndarray` object for storing and processing numerical
data efficiently.

NumPy is commonly used for:
- Numerical calculations
- Arrays and matrices
- Mathematical operations
- Statistical operations
- Data processing

In [6]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)
1
int64

## NumPy Array Operations

NumPy allows us to perform mathematical operations directly on arrays.
These operations are faster and more convenient than performing the same
operations using Python loops.

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 10)

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [1. 2. 3. 4. 5.]

## NumPy Indexing and Slicing

Indexing is used to access individual elements of an array, while slicing
is used to access a range of elements.

In [8]:
print("First element:", arr[0])
print("Last element:", arr[-1])
print("First three elements:", arr[:3])
print("Elements from index 2:", arr[2:])

First element: 10
Last element: 50
First three elements: [10 20 30]
Elements from index 2: [30 40 50]

## NumPy 2D Arrays

A 2D NumPy array consists of rows and columns and can be used to
represent tabular or matrix-like data.

The structure of a 2D array can be examined using properties such as
shape, ndim, and size.

In [9]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)
print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Size:", data.size)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
Dimensions: 2
Size: 9

## Indexing and Slicing in 2D Arrays

In a 2D array, an element can be accessed using its row and column
index. Python uses zero-based indexing.

In [10]:
print("First element:", data[0, 0])
print("Second row:", data[1])
print("Second column:", data[:, 1])
print("First two rows:")
print(data[:2])

First element: 10
Second row: [40 50 60]
Second column: [20 50 80]
First two rows:
[[10 20 30]
 [40 50 60]]

## Statistical Operations with NumPy

NumPy provides built-in functions for common statistical calculations
such as mean, median, minimum, maximum, and standard deviation.

In [11]:
values = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(values))
print("Median:", np.median(values))
print("Minimum:", np.min(values))
print("Maximum:", np.max(values))
print("Standard deviation:", np.std(values))

Mean: 30.0
Median: 30.0
Minimum: 10
Maximum: 50
Standard deviation: 14.142135623730951

## Reshaping NumPy Arrays

Reshaping changes the structure of an array without changing its data.

The total number of elements must remain the same before and after
reshaping.

In [12]:
arr = np.arange(1, 13)

print("Original array:")
print(arr)

reshaped = arr.reshape(3, 4)

print("\nReshaped array:")
print(reshaped)

print("\nNew shape:", reshaped.shape)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

New shape: (3, 4)

## Conditional Filtering

NumPy allows us to filter array elements using conditions.

This is useful when we need to select observations that satisfy a
specific condition.

In [14]:
values = np.array([10, 25, 40, 15, 60, 30])

filtered = values[values > 30]

print("Original values:", values)
print("Values greater than 30:", filtered)

Original values: [10 25 40 15 60 30]
Values greater than 30: [40 60]

## NumPy Summary

In this section, we learned:

- NumPy arrays and `ndarray`
- Array properties such as shape, dimensions, size, and data type
- Array indexing and slicing
- 2D arrays
- Mathematical and statistical operations
- Array reshaping
- Conditional filtering

These operations form the foundation for numerical data processing in
Python.

## What is Pandas?

Pandas is a Python library used for data manipulation and analysis.

It provides two important data structures:

- Series: One-dimensional labeled data
- DataFrame: Two-dimensional tabular data

Pandas is commonly used for data cleaning, filtering, transformation,
and analysis.

In [15]:
import pandas as pd

series = pd.Series([10, 20, 30, 40, 50])

print(series)
print("\nType:", type(series))

0    10
1    20
2    30
3    40
4    50
dtype: int64

Type: <class 'pandas.Series'>

## Pandas Series Indexing

A Series can be accessed using its index.

By default, Pandas assigns integer indexes starting from 0.

In [16]:
print("First value:", series[0])
print("Second value:", series[1])
print("Last value:", series[4])

First value: 10
Second value: 20
Last value: 50

In [17]:
marks = pd.Series(
    [85, 90, 78, 92],
    index=["Maths", "Physics", "Chemistry", "English"]
)

print(marks)
print("\nPhysics marks:", marks["Physics"])

Maths        85
Physics      90
Chemistry    78
English      92
dtype: int64

Physics marks: 90

## What is a DataFrame?

A DataFrame is a two-dimensional labeled data structure in Pandas.

It is similar to a table with rows and columns.

DataFrames are commonly used for storing, manipulating, and analyzing datasets.

In [18]:
data = {
    "Name": ["Aman", "Riya", "Kartik", "Neha"],
    "Age": [21, 22, 20, 23],
    "Marks": [85, 92, 78, 88]
}

df_demo = pd.DataFrame(data)

print(df_demo)

     Name  Age  Marks
0    Aman   21     85
1    Riya   22     92
2  Kartik   20     78
3    Neha   23     88

In [19]:
print("Shape:", df_demo.shape)
print("Columns:", df_demo.columns)
print("Data types:")
print(df_demo.dtypes)

Shape: (4, 3)
Columns: Index(['Name', 'Age', 'Marks'], dtype='str')
Data types:
Name       str
Age      int64
Marks    int64
dtype: object

## Inspecting a DataFrame

Pandas provides useful functions to quickly understand a dataset.

- `head()` shows the first rows.
- `tail()` shows the last rows.
- `info()` shows column names, data types, and non-null values.
- `describe()` gives statistical summary of numerical columns.

In [20]:
df = pd.read_csv("../data/WineQT.csv")

print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality  Id
0      9.4        5   0
1      9.8        5   1
2      9.8        5   2
3      9.8        6   3
4      9.4        5   4

In [21]:
print(df.tail())

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1138            6.3             0.510         0.13             2.3      0.076
1139            6.8             0.620         0.08             1.9      0.068
1140            6.2             0.600         0.08             2.0      0.090
1141            5.9             0.550         0.10             2.2      0.062
1142            5.9             0.645         0.12             2.0      0.075

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1138                 29.0                  40.0  0.99574  3.42       0.75
1139                 28.0                  38.0  0.99651  3.42       0.82
1140                 32.0                  44.0  0.99490  3.45       0.58
1141                 39.0                  51.0  0.99512  3.52       0.76
1142                 32.0                  44.0  0.99547  3.57       0.71

      alcohol  quality    Id
1138     11.0        6  1592
1139      9.5        6  1593
1140     10.5        5  1594
1141     11.2        6  1595
1142     10.2        5  1597

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [23]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

## Selecting Columns

Pandas allows us to select one or more columns from a DataFrame.

Selecting specific columns is useful when we want to focus on particular features during data analysis.

In [24]:
# Select one column
print(df["alcohol"])

0        9.4
1        9.8
2        9.8
3        9.8
4        9.4
        ...
1138    11.0
1139     9.5
1140    10.5
1141    11.2
1142    10.2
Name: alcohol, Length: 1143, dtype: float64

In [25]:
# Select multiple columns
selected = df[["alcohol", "pH", "quality"]]

print(selected.head())

   alcohol    pH  quality
0      9.4  3.51        5
1      9.8  3.20        5
2      9.8  3.26        5
3      9.8  3.16        6
4      9.4  3.51        5

## Selecting Rows

Rows can be selected using conditions.

This is useful for filtering observations based on specific requirements.

In [26]:
# Wines with quality greater than 6
high_quality = df[df["quality"] > 6]

print(high_quality.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
7             7.3              0.65         0.00             1.2      0.065
8             7.8              0.58         0.02             2.0      0.073
12            8.5              0.28         0.56             1.8      0.092
27            8.1              0.38         0.28             2.1      0.066
89            8.0              0.59         0.16             1.8      0.065

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
7                  15.0                  21.0   0.9946  3.39       0.47
8                   9.0                  18.0   0.9968  3.36       0.57
12                 35.0                 103.0   0.9969  3.30       0.75
27                 13.0                  30.0   0.9968  3.23       0.73
89                  3.0                  16.0   0.9962  3.42       0.92

    alcohol  quality   Id
7      10.0        7    7
8       9.5        7    8
12     10.5        7   16
27      9.7        7   37
89     10.5        7  128

## Selecting Rows and Columns with loc and iloc

`loc` is used for label-based selection.

`iloc` is used for position-based selection using integer indexes.

In [27]:
# Using loc
print(df.loc[0, "alcohol"])
print(df.loc[0:4, ["alcohol", "pH", "quality"]])

9.4
   alcohol    pH  quality
0      9.4  3.51        5
1      9.8  3.20        5
2      9.8  3.26        5
3      9.8  3.16        6
4      9.4  3.51        5

In [28]:
# Using iloc
print(df.iloc[0, 10])
print(df.iloc[0:5, 10:13])

9.4
   alcohol  quality  Id
0      9.4        5   0
1      9.8        5   1
2      9.8        5   2
3      9.8        6   3
4      9.4        5   4

## Filtering with Multiple Conditions

Pandas allows us to filter rows using multiple conditions.

- `&` means AND
- `|` means OR
- Each condition should be written inside parentheses.

In [29]:
# AND condition
filtered = df[(df["quality"] >= 6) & (df["alcohol"] > 10)]

print(filtered.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
12            8.5             0.280         0.56             1.8      0.092
26            7.8             0.600         0.14             2.4      0.086
30            7.5             0.490         0.20             2.6      0.332
38            7.6             0.510         0.15             2.8      0.110
48            8.0             0.705         0.05             1.9      0.074

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
12                 35.0                 103.0   0.9969  3.30       0.75
26                  3.0                  15.0   0.9975  3.42       0.60
30                  8.0                  14.0   0.9968  3.21       0.90
38                 33.0                  73.0   0.9955  3.17       0.63
48                  8.0                  19.0   0.9962  3.34       0.95

    alcohol  quality  Id
12     10.5        7  16
26     10.8        6  36
30     10.5        6  42
38     10.2        6  54
48     10.5        6  69

In [30]:
# OR condition
filtered = df[(df["quality"] >= 7) | (df["alcohol"] > 13)]

print(filtered.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
7             7.3              0.65         0.00             1.2      0.065
8             7.8              0.58         0.02             2.0      0.073
12            8.5              0.28         0.56             1.8      0.092
27            8.1              0.38         0.28             2.1      0.066
32            4.6              0.52         0.15             2.1      0.054

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
7                  15.0                  21.0   0.9946  3.39       0.47
8                   9.0                  18.0   0.9968  3.36       0.57
12                 35.0                 103.0   0.9969  3.30       0.75
27                 13.0                  30.0   0.9968  3.23       0.73
32                  8.0                  65.0   0.9934  3.90       0.56

    alcohol  quality  Id
7      10.0        7   7
8       9.5        7   8
12     10.5        7  16
27      9.7        7  37
32     13.1        4  45

In [31]:
# Multiple columns with conditions
filtered = df[
    (df["quality"] >= 6) &
    (df["pH"] < 3.5) &
    (df["alcohol"] > 10)
]

print(filtered.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
12            8.5             0.280         0.56             1.8      0.092
26            7.8             0.600         0.14             2.4      0.086
30            7.5             0.490         0.20             2.6      0.332
38            7.6             0.510         0.15             2.8      0.110
48            8.0             0.705         0.05             1.9      0.074

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
12                 35.0                 103.0   0.9969  3.30       0.75
26                  3.0                  15.0   0.9975  3.42       0.60
30                  8.0                  14.0   0.9968  3.21       0.90
38                 33.0                  73.0   0.9955  3.17       0.63
48                  8.0                  19.0   0.9962  3.34       0.95

    alcohol  quality  Id
12     10.5        7  16
26     10.8        6  36
30     10.5        6  42
38     10.2        6  54
48     10.5        6  69

## Sorting DataFrame

Pandas allows us to sort rows based on one or more columns.

`sort_values()` is used to arrange data in ascending or descending order.

In [32]:
# Sort by alcohol in ascending order
sorted_df = df.sort_values("alcohol")

print(sorted_df[["alcohol", "quality"]].head())

      alcohol  quality
388       8.4        6
368       8.4        3
1023      8.5        5
263       8.7        6
1051      8.8        5

In [33]:
# Sort by alcohol in descending order
sorted_df = df.sort_values("alcohol", ascending=False)

print(sorted_df[["alcohol", "quality"]].head())

     alcohol  quality
462     14.9        5
419     14.0        8
589     14.0        7
898     14.0        6
98      14.0        6

## Creating a New Column

A new column can be created by assigning a value or calculation to a new column name.

In [34]:
df["alcohol_percentage"] = df["alcohol"]

print(df[["alcohol", "alcohol_percentage"]].head())

   alcohol  alcohol_percentage
0      9.4                 9.4
1      9.8                 9.8
2      9.8                 9.8
3      9.8                 9.8
4      9.4                 9.4

## Removing Columns

The `drop()` method is used to remove unwanted rows or columns from a DataFrame.

Removing unnecessary columns is an important part of data cleaning and preprocessing.

In [35]:
# Remove the column we created for practice
df_clean = df.drop(columns=["alcohol_percentage"])

print(df_clean.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076
1            7.8              0.88         0.00             2.6      0.098
2            7.8              0.76         0.04             2.3      0.092
3           11.2              0.28         0.56             1.9      0.075
4            7.4              0.70         0.00             1.9      0.076

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56
1                 25.0                  67.0   0.9968  3.20       0.68
2                 15.0                  54.0   0.9970  3.26       0.65
3                 17.0                  60.0   0.9980  3.16       0.58
4                 11.0                  34.0   0.9978  3.51       0.56

   alcohol  quality  Id
0      9.4        5   0
1      9.8        5   1
2      9.8        5   2
3      9.8        6   3
4      9.4        5   4

## Creating a Derived Column

A derived column is created from existing columns.

Derived features are commonly used in data processing to represent
information in a more useful form.

In [36]:
df["alcohol_level"] = np.where(
    df["alcohol"] >= 10,
    "High",
    "Low"
)

print(df[["alcohol", "alcohol_level"]].head())

   alcohol alcohol_level
0      9.4           Low
1      9.8           Low
2      9.8           Low
3      9.8           Low
4      9.4           Low

## Value Counts

`value_counts()` counts the frequency of each unique value in a column.

It is particularly useful for understanding categorical or discrete variables.

In [37]:
df["quality"].value_counts().sort_index()

quality
3      6
4     33
5    483
6    462
7    143
8     16
Name: count, dtype: int64

In [38]:
df["alcohol_level"].value_counts()

alcohol_level
High    658
Low     485
Name: count, dtype: int64

## Grouping and Aggregation

The `groupby()` method is used to divide data into groups based on the
values of one or more columns.

After grouping, aggregation functions such as `mean()`, `min()`, `max()`,
and `count()` can be used to summarize each group.

This is commonly used in real-world data analysis to compare groups.

In [39]:
df.groupby("quality")["alcohol"].mean()

quality
3     9.691667
4    10.260606
5     9.902277
6    10.655339
7    11.482634
8    11.937500
Name: alcohol, dtype: float64

In [40]:
df.groupby("quality")["alcohol"].agg(
    ["count", "mean", "min", "max"]
)

         count       mean  min   max
quality
3            6   9.691667  8.4  10.9
4           33  10.260606  9.0  13.1
5          483   9.902277  8.5  14.9
6          462  10.655339  8.4  14.0
7          143  11.482634  9.2  14.0
8           16  11.937500  9.8  14.0

In [41]:
df.groupby("quality")[["alcohol", "pH", "density"]].mean()

           alcohol        pH   density
quality
3         9.691667  3.361667  0.997682
4        10.260606  3.391212  0.996669
5         9.902277  3.302091  0.997073
6        10.655339  3.323788  0.996610
7        11.482634  3.287133  0.996071
8        11.937500  3.240625  0.995553

### Named Aggregation

Named aggregation allows us to give meaningful names to calculated
statistics, making the resulting table easier to understand.

In [42]:
quality_summary = df.groupby("quality").agg(
    average_alcohol=("alcohol", "mean"),
    average_pH=("pH", "mean"),
    average_density=("density", "mean"),
    number_of_wines=("quality", "count")
)

quality_summary

         average_alcohol  average_pH  average_density  number_of_wines
quality
3               9.691667    3.361667         0.997682                6
4              10.260606    3.391212         0.996669               33
5               9.902277    3.302091         0.997073              483
6              10.655339    3.323788         0.996610              462
7              11.482634    3.287133         0.996071              143
8              11.937500    3.240625         0.995553               16

## Missing Data Handling

Missing values are common in real-world datasets.

Pandas provides methods to identify, count, remove, and replace missing
values.

Common methods include:

- `isnull()` → identifies missing values
- `sum()` → counts missing values
- `dropna()` → removes rows or columns containing missing values
- `fillna()` → replaces missing values

In [43]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
alcohol_percentage      0
alcohol_level           0
dtype: int64

In [45]:
df.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
Id                      False
alcohol_percentage      False
alcohol_level           False
dtype: bool

In [46]:
sample = pd.Series([10, 20, np.nan, 40, 50])

print("Original:")
print(sample)

print("\nAfter filling:")
print(sample.fillna(sample.mean()))

Original:
0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64

After filling:
0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64

In [47]:
sample = pd.Series([10, 20, np.nan, 40, 50])

print(sample.dropna())

0    10.0
1    20.0
3    40.0
4    50.0
dtype: float64

### Observation

The WineQT dataset does not contain missing values, so no missing-value
treatment is required for this dataset.

The examples above demonstrate how `fillna()` and `dropna()` can be used
when missing values are present in a real-world dataset.

## Duplicate Data

Duplicate records can occur when the same observation is stored more than
once.

Duplicate data can affect analysis and may lead to incorrect conclusions,
so it is important to identify and handle duplicates during data
processing.

In [48]:
df.duplicated().sum()

np.int64(0)

In [49]:
df[df.duplicated()]

Empty DataFrame
Columns: [fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, quality, Id, alcohol_percentage, alcohol_level]
Index: []

In [50]:
df_no_duplicates = df.drop_duplicates()

print("Original rows:", len(df))
print("Rows after removing duplicates:", len(df_no_duplicates))

Original rows: 1143
Rows after removing duplicates: 1143

## Renaming Columns

The `rename()` method is used to change column names in a DataFrame.

Clear and meaningful column names make data easier to understand and work with.

In [51]:
df_renamed = df.rename(columns={
    "fixed acidity": "fixed_acidity",
    "volatile acidity": "volatile_acidity",
    "citric acid": "citric_acid",
    "residual sugar": "residual_sugar"
})

print(df_renamed.columns)

Index(['fixed_acidity', 'volatile_acidity', 'citric_acid', 'residual_sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id', 'alcohol_percentage',
       'alcohol_level'],
      dtype='str')

## Filtering Data with query()

The `query()` method provides a convenient way to filter rows using
conditions written as a string.

In [52]:
high_quality = df.query("quality >= 7")

print(high_quality[["alcohol", "quality"]].head())

    alcohol  quality
7      10.0        7
8       9.5        7
12     10.5        7
27      9.7        7
89     10.5        7

In [53]:
high_quality = df.query("quality >= 7")

print(high_quality[["alcohol", "quality"]].head())

    alcohol  quality
7      10.0        7
8       9.5        7
12     10.5        7
27      9.7        7
89     10.5        7

## Practical Data Processing Workflow

A basic data-processing workflow includes:

1. Loading the dataset
2. Inspecting the data
3. Checking missing values and duplicates
4. Filtering required observations
5. Grouping and summarizing data
6. Creating a final summary

In [56]:
# 1. Load dataset
df = pd.read_csv("../data/WineQT.csv")

In [57]:
# 2. Inspect dataset
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (1143, 13)

Columns:
['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality', 'Id']

In [59]:
# 3. Check missing values and duplicates
print("\nMissing values:")
print(df.isnull().sum().sum())

Missing values:
0

In [60]:
# 3. Duplicate values
print("\nDuplicate rows:")
print(df.duplicated().sum())

Duplicate rows:
0

In [61]:
# 4. Filter high-quality wines
high_quality = df[df["quality"] >= 7]

print("High-quality wines:", len(high_quality))
print(high_quality[["alcohol", "pH", "quality"]].head())

High-quality wines: 159
    alcohol    pH  quality
7      10.0  3.39        7
8       9.5  3.36        7
12     10.5  3.30        7
27      9.7  3.23        7
89     10.5  3.42        7

In [62]:
# 5. Group by quality and calculate averages
summary = df.groupby("quality").agg(
    average_alcohol=("alcohol", "mean"),
    average_pH=("pH", "mean"),
    average_density=("density", "mean"),
    number_of_wines=("quality", "count")
)

summary

         average_alcohol  average_pH  average_density  number_of_wines
quality
3               9.691667    3.361667         0.997682                6
4              10.260606    3.391212         0.996669               33
5               9.902277    3.302091         0.997073              483
6              10.655339    3.323788         0.996610              462
7              11.482634    3.287133         0.996071              143
8              11.937500    3.240625         0.995553               16

## Conclusion

NumPy and Pandas provide essential tools for numerical computation,
data manipulation, filtering, cleaning, grouping, and statistical analysis.

These operations form the foundation of data processing in Python.